### ISSUE TITLE
Title & editors on landing page

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#202]
@wsalesky George is writing something to replace the lorem ipsum on the landing page. However, we also would like the title and editors to appear as well. My first thought would be to put the title into the maroon box at the top of the landing page, left adjusted on two lines as follows:

Gorgias Encyclopedic Dictionary of the Syriac Heritage:
Electronic Edition

Below that, outside the maroon box, I think we should have editors listed in two sections (I can't decide if they should go one above the other or side by side, like on BHSE (http://syriaca.org/bhse/index.html). The text would be:

Editors of Print Edition:
Sebastian P. Brock 
Aaron M. Butts 
George A. Kiraz 
Lucas Van Rompay

Digital Edition:
Ute Possekel, Digital Editor
Daniel L. Schwartz, Technical Editor
David A. Michelson, Technical Editor
Winona Salesky, Technical Editor

This is just a working idea and you likely have a better idea. If so, don't hesitate to make suggestions or (if it's not too much work) make a couple of versions.

By the way, we've given George some prose explaining what everyone did in order to create the digital edition and he will incorporate that into what he writes for the landing page.

Thanks Winona

**Comment by dlschwartz** [comment]
@wsalesky Let's reduce this issue to the following (cut and pasted from above).

My first thought would be to put the title into the maroon box at the top of the landing page, left adjusted on two lines as follows:

Gorgias Encyclopedic Dictionary of the Syriac Heritage:
Electronic Edition

**Comment by wsalesky** [comment]
@dlschwartz  Can we keep this as one line? I don't like the aesthetics of having those as two lines on every page, it takes up a lot of screen real estate.

**Comment by dlschwartz** [comment]
One line sounds good to me.

**Comment by wsalesky** [comment]
Added to the banner. The banner does not show up on the landing page, Should I change the heading from: 

> e-GEDSH: An Online Encyclopedic Dictionary of the Syriac Heritage

to:

> Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition

**Comment by dlschwartz** [comment]
@wsalesky I wanted to propose something a little different from what George had suggested. Sorry if I wasn't clear about that. I would basically like to keep what we have on the pages of the body: 
![banner](https://user-images.githubusercontent.com/4984270/39146576-c8d37246-46fc-11e8-9355-4b3c8aa98ed9.JPG)
Perhaps we should change this to include: "Gorgias Encyclopedic Dictionary of the Syriac Heritage: Electronic Edition" throughout all pages. 

On landing page, this would then just appear inside the maroon banner without a title appearing above the "blurb". Does that make sense? George might not like it but what he proposes is a different title than what we have in the "how to cite" sections. Also, the language "An Online Encyclopedic..." suggests to me something different from an electronic edition of what currently exists in print. 

Let's try a consistent banner text throughout all pages (even if the banner itself is taller on the landing page) and the removal of the title immediately above the "blurb".

**Comment by dlschwartz** [comment]
@wsalesky We're so close but I feel like it needs to be bigger on the landing page. Would something like this work without messing up the banner on the other pages?
![landingbanner](https://user-images.githubusercontent.com/4984270/39191606-ed6b0b82-479c-11e8-89d4-da41e2c5910b.JPG)

**Comment by wsalesky** [comment]
How about now? (Do a hard refresh)

**Comment by dlschwartz** [comment]
I have the "Gorgias" indented a bit from the "Electronic." 
![landingbanner](https://user-images.githubusercontent.com/4984270/39192089-03da3a04-479e-11e8-8e2a-3d0e6f2ed86f.JPG)
Can we move the "Electronic" over under the "Gorgias"? Also, can you think of anything to make it pop a pit more? Maybe centering it vertically within the marron box? I don't want to go too big as it will make it harder to scale. Do you have any additional thoughts?

**Comment by wsalesky** [comment]
A hard refresh should fix the indent issue. <img width="458" alt="screen shot 2018-04-24 at 10 05 08 am" src="https://user-images.githubusercontent.com/1168206/39192385-0ba567dc-47a7-11e8-9f6a-130ad56f068d.png">

I will see if I can come up with something to make it pop more. Leave this open as a reminder

**Comment by dlschwartz** [comment]
@wsalesky Weird, I still have the indent after multiple hard refreshes. I closed the tab and then my browser as well. I reopened the browser and did another hard refresh and I still have the indent. I'm in Chrome on a PC if that matters. By the way, I checked my phone and can't tell there because the main title breaks down into five lines of text but the "Electronic Edition" gets cut off at the bottom so I can't tell how it indents.

**Comment by dlschwartz** [comment]
@wsalesky I've got it now. I think this looks great. Let's leave it as is for the moment. I'm slightly worried George will want changes. But I really like it as is. Thanks Winona.

**Comment by dlschwartz** [comment]
@wsalesky Feel free to close this when you're happy too.

**Comment by wsalesky** [comment]
@dlschwartz I think it is okay.
