### ISSUE TITLE
GEDSH LOD box

### ISSUE THREAD

**Issue by dlschwartz** [srophe/e-gedsh#241]
@wsalesky I know you're doing some work on the LOD box right now so this might be expected. I just want you to know what I'm seeing in GEDSH right now.

Some articles with syriaca URIs don't have a LOD box:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Kfar-Helda
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Konat-Matta

Some articles have no count on the headword and what appears to be an incorrect count of the number of "other topics":
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Khouri-Sarkis-Gabriel
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Khoury-Asmar

In other cases, things look fine:
http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Khamis-bar-Qardahe

**Comment by wsalesky** [comment]
@dlschwartz Thanks, looks like there is an issue with what is being indexed in the triple-store. I will take a look today.

**Comment by wsalesky** [comment]
I think this has been fixed. A combination of needing to re-index the triple-store and also to adjust the SPARQL query. Let me know if you find any other entries that should have results and do not. I'm still refining the SPARQL.

**Comment by dlschwartz** [comment]
Great, thanks Winona. I'll test things and let you know if I find any problems.

**Comment by dlschwartz** [comment]
@wsalesky Now I've got some different problems. 

See http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Babai-of-Nisibis. Here we get a count of 2 related resources but when we expand we see three headings. They are all the same syriaca.org URI however. Is there any chance we're pulling in multiple name variants as separate related resources? 

We have a similar problem with the counts and with pulling in multiple name variants here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Baghdad. 

Here we get a count of 3 related resources, which is correct, but we have each one appearing twice, once with a Syriac name variant and once with an English name variant.

**Comment by dlschwartz** [comment]
Also, I have an odd problem with the "Show other resources" button on at least one article: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Baghdad. On clicking once, I get only a link to click with the text "See more...". None of the entries loads. When I click on that link they appear.

In the Antioch article (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Antioch) I get Arabic name variants.

Also, in the Antioch article, when I expand the show other resources button, it displays all of the resources but clicking the "Less" and the "See more..." links at the bottom has no impact on the display of resources. The links just toggle back and forth.

**Comment by wsalesky** [comment]
@dlschwartz Thanks! You have solved the duplicate results issue! It is pulling the name variants, also sometimes there is no english name, which was suppressing some results. I'm trying to figure out the best way to deal with these issues.  Will update shortly, I hope.

**Comment by wsalesky** [comment]
@dlschwartz I think I fixed them all. Let me know if not. There is a combination of places where the script can go wrong, either SPARQL or the JavaScript. I think I've patched all the JavaScript holes, so now we should just be dealing with making adjustments to the SPARQL as needed.

**Comment by dlschwartz** [comment]
@wsalesky It so nice to stumble into a solution rather than my normal stumbling into trouble. Excellent. Things are looking much better, thanks.

I still get the "Less" and "See more..." toggle issue. Here's the first place I noticed it: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Abdullah-II-Sattuf. I do remember that in SPEAR browse, for example, that less/more feature was always a bit buggy. Not sure if that's a Chrome thing or a PC thing. I remember posting about feature in the past when everyone else said it was working fine. 

Also, and this only happens infrequently, a count problem appears. See here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Abdulmasih-II and here: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Abdisho-bar-Bahriz. In each case the stated count of related resources is one higher than the count that appears when "Show other resources" is selected.

**Comment by wsalesky** [comment]
@dlschwartz I think the count mismatch is for resources that do not have any linked data available. We can remove the count and just say 'Resources related to other topics in this article.'

**Comment by dlschwartz** [comment]
@wsalesky @davidamichelson Let's loop Dave in on this. I like the solution but he may prefer something else.

**Comment by davidamichelson** [comment]
I’ll try to look at this tomorrow

**Comment by dlschwartz** [comment]
@wsalesky There might be an explanation I'm not thinking of, but I don't find LOD in the Antioch article (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Antioch) for the following:
http://syriaca.org/person/2244
http://syriaca.org/person/2284
http://syriaca.org/person/2008
http://syriaca.org/person/2245
There might be a few more. Any chance that the discrepancy between the count and the number listed is because some aren't appearing?

**Comment by wsalesky** [comment]
Thanks, I'm going to try rerunning the RDF generation. I'm not sure everything is getting indexed.

**Comment by wsalesky** [comment]
@dlschwartz I think this is fixed. Reopen if not.

**Comment by dlschwartz** [comment]
I hate to re-open this, but here it is. 

See: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Abdisho-bar-Bahriz
The TEI contains http://syriaca.org/person/782. It gets counted for the LOD box but doesn't appear in the list even though there seems to be plenty of data in Syriaca.org.

See also: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Baghdad. The count here is also correct but the following don't appear even though we have Syriaca.org data for them: http://syriaca.org/person/139; http://syriaca.org/person/180; http://syriaca.org/person/236; http://syriaca.org/place/219; http://syriaca.org/place/13.

**Comment by wsalesky** [comment]
@dlschwartz Thanks I will take a look.

**Comment by wsalesky** [comment]
@dlschwartz I figured out the problem, it is in the RDF generation. I am rerunning, this will take a little while as I have to rerun all the data. This should solve the miss count issue as well. Check back this afternoon.

**Comment by wsalesky** [comment]
@dlschwartz I think this has been resolved. Close if you agree.

**Comment by dlschwartz** [comment]
@wsalesky Things look so good and we are so close! It looks like the re-indexing has worked and we're getting an accurate account of what's in Syriaca.org date, which is great! I'm afraid there's still a problem with the count. I started in the B's and advanced through the entries looking at the LOD boxes. In every instance where there are 10 or fewer related resources, the count matches the number of resources that display when you select "Show other resources." In every instance where there were more than 10 related resources, the count does not match, it's one too many. I see this in every instance. Furthermore, in this article (http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry/Chaldean-Catholic-Church) it lists 11 but there are only 10 and the "Less" and "See more..." buttons just toggle back and forth with no change in what's displayed. Is there any chance that there is something wonky going on with that feature of the box? I'm late leaving the office and can look again first thing in the morning to compare the Syriaca.org URIs in the TEI with the links that display. We'll crack this thing! Thanks for all your hard work on this Winona.

**Comment by wsalesky** [comment]
@dlschwartz Okay, that was a bug in the XQuery. Should be fixed. Please review.

**Comment by dlschwartz** [comment]
@wsalesky @davidamichelson IT WORKS! I think we're done. Excellent! I will ask George to share e-GEDSH with the print editors now. Many thanks Winona!

**Comment by davidamichelson** [comment]
Yes, well done Winona!
